[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
panic-abort-tests = true

[build]
target = "x86_64_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[env]
GTK_PATH = "/usr/lib/x86_64-linux-gnu/gtk-3.0"
GTK_MODULES = ""

[alias]
run-os = "xrun"

[xrun]
args = [
    "bootimage",
    "--",
    "qemu-system-x86_64",
    "-drive", "format=raw,file=target/x86_64_os/debug/bootimage-oxideOS.bin"
]
